src/character-tracker.ts, src/characters/action-context.ts, src/characters/assets.ts, src/characters/lens.test.ts, src/characters/lens.ts, src/utils/ui/info.ts
Switches from `marked_abilities: [1,2]` to `abilities: [true, true, false]` for asset abilities representation.
(Since this will break existing characters with assets, it also adds very slightly more useful error messages when loading an invalid character)
Fixes #16
=> Use boolean array for marked abilities

src/oracles/command.ts, src/oracles/oracle-modal.ts
Looks like `Workspace.getActiveFileView()` does what we want-- seems to track the last editor that the cursor was in! I'm wondering if it's the same underlying thing used by the left File sidebar-- that definitely has the behavior that we want, so if this doesn't work out, figuring that out via the JS debugger may be a next step.
=> Wire up the sidebar oracles

.vscode/settings.json, src/tracks/clock-file.ts, src/tracks/progress.test.ts, src/tracks/progress.ts, src/tracks/writer.ts, src/utils/obsidian.ts, src/utils/update.ts, src/utils/zodutils.test.ts, src/utils/zodutils.ts, test-vault/Clocks/Test Clock.md, test-vault/Progress/Example Vow.md
Introduces a zod helper `normalizeKeys` that allows us to make case-insensitive object schemas, which this uses to preserve backwards compatibility.
Fixes #56
=> Use lowercase for clock and progress track keys

src/tracks/progress.test.ts, src/tracks/progress.ts
=> ProgressTrack: enforce upper/lower bound when using advancement methods

src/settings/index.ts, src/settings/ui.ts, src/tracks/commands.ts, src/tracks/progress-create.ts, src/utils/ui/settings/folder.ts, src/utils/ui/settings/generic-text-suggest.ts
Fixes #46
Adopts the following pattern which we can eventually use for other creators if we like it
- You can set a "default progress track folder" in the settings. This defaults to the old value of "Progress"
- In the Progress track creation modal, you can pick an alternative folder to put this particular track into. I thought this might be helpful if you wanted to organize your tracks by, i dunno, type or location
- In any event, if the folder you specify does not exist, it will be created
=> Make progress track creation folder configurable

src/character-tracker.ts, src/characters/action-context.ts, src/characters/commands.ts, src/characters/lens.test.ts, src/characters/lens.ts, src/characters/meter-commands.ts, src/index.ts, src/indexer/index-impl.ts, src/indexer/indexer.ts, src/indexer/manager.ts, src/moves/action/index.ts, src/tracks/clock-block.ts, src/tracks/clock-file.ts, src/tracks/context.ts, src/tracks/progress.ts, src/tracks/select-clock.ts, src/tracks/track-block.ts, src/utils/either.ts
Overhauls indexers to preserve errors.
As part of changing indexers, this replaces CharacterTracker with the same Index that Clocks and Tracks use. To abstract away that change, more code that used CharacterTracker directly now works through an ActionContext.
Fixes #81
=> Make all indexers track errors

src/api.ts, src/characters/commands.ts, src/clocks/clock-block.ts, src/clocks/clock-file.ts, src/index.ts, src/indexer/index-impl.ts, src/indexer/index-interface.ts, src/indexer/index.ts, src/indexer/indexer.ts, src/tracks/context.ts, src/tracks/indexer.ts, src/tracks/progress.ts, src/tracks/track-block.ts, src/utils/filename.ts, src/utils/filtered-map.ts, src/utils/strings.ts
`Index` now emits a `changed` event when an entry is added, deleted, or updated. The track/clock blocks are reimplemented on top of this, so they render reliably as soon as the file is indexed.
Fixes #117
=> Use index change events to re-render clock and track blocks

src/entity/command.ts, src/entity/modal.ts, src/entity/specs.ts, src/index.ts, src/mechanics/node-builders.ts, src/sidebar/oracles.ts
* Use "oracle-group" for entity rendering in the journal
* Add an option to create a new file for an entity-- currently uses hardcoded Handlebars template which creates a table
* Use entity generation as command for rolling an oracle collection in the sidebar. If proper entity generation config exists, use it. If not, create a placeholder one with no first look fields.
Fixes #36
Fixes #83
=> Improve entity generation

src/truths/truth-block.ts
This makes things less jumpy and sets you up to start typing right away.
=> set the cursor position after interaction with truth blocks

src/entity/specs.ts
Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/204
=> use smart quotes for callsigns to avoid Windows filename issue

src/datastore/parsers/table.ts, src/utils/strings.ts
They go against Obsidian guidelines
=> get rid of lookbehinds

README.md
I needed to run `pnpm install` before 'pnpm build`. Added to README.md in case this applies to everyone. ~Ars
=> Add `pnpm install` to build instructions

src/characters/action-context.ts, src/characters/assets.ts, src/characters/display.ts, src/characters/lens.test.ts, src/characters/lens.ts, src/characters/meter-commands.ts, src/moves/action/index.ts, src/utils/ensure-unique.ts, test-vault/characters/Ash Barlowe.md
This gives asset meters the label `<asset name> / <meter label>` in the meter lists, as well as in the mechanics node outputs.
It also fixes a bug I noticed where meters with a value of 0 would behave as if a value didn't exist (prompting you for a value, etc).
Fixes #362
=> Give asset meters unique keys and labels

src/characters/character-block.ts, src/clocks/clock-block.ts, src/indexer/index-impl.ts, src/indexer/index-interface.ts, src/indexer/indexer.ts, src/indexer/manager.ts, src/tracks/track-block.ts, src/utils/ui/tracked-entity-renderer.ts
- Fixes a bug where renames were not actually processed ever in the indexer DOH!
- Adds a rename event to the tracked entity indexes, so that renderers can update the path they track
- Introduces an abstract base class for tracked entity renderers that handles the repetitive work (including the new rename handler)
Fixes #286
=> Handle renames in tracked entity blocks

data/sundered-isles.supplement.json, data/sundered-isles.supplement.yaml, package.json, src/datastore.ts, src/entity/command.ts, src/entity/specs.ts, src/sidebar/oracles.ts
Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/373
Cursed oracles won't be supported yet. That's coming with #349
=> add entities for sundered isles

src/entity/specs.ts
Ahh, sorry, I caught this seconds before your approved the last one, without this it causes 'First Look' gen to bomb out and probably other bad things.
=> Added Nullability to SI Settlement NameGen

src/clocks/clock-create-modal.ts, src/entity/modal.ts, src/settings/ui.ts, src/tracks/progress-create.ts, src/truths/command.ts, src/utils/ui/settings/folder.ts
This fixes an issue where if you select the helper auto fill text on the folder selection input it doesn't register that it was selected so entities, progress tracks etc... don't actually get created where a user would expect them to.
=> Fix bug when selecting suggested folder

src/datastore.ts, src/settings/ui.ts, src/styles.css
This is a fix for #292  and #293 . For the first it just pops a notice saying the file is un-parsable. For the second it will not save an invalid path (fixing the notifications for each typed letter in the box), but does try to tell the user it is invalid by highighting the field red onBlur(). Honestly, obsidian could give us a little more in the way of tooling for validation on their settings object, but this is a good-faith attempt to let a user know something is wrong.
=> Fixes for Saving Homebrew Folder

src/truths/command.ts
This is a temporary thing while we get around to playsets, because it's pretty painful/annoying to be double-generating truths.
=> stop writing out starforged truths if SI is enabled

src/datastore/parsers/datasworn/oracles.ts, src/entity/modal.ts, src/model/oracle.ts
This adds support for re-roller oracles entries for entities when it is specified in Datasworn. In short, when more than 1 roll is recommended, it shows how many rolls are suggested and then when you click the dice icon it switches to a 'circle-arrow' icon and when clicked again it appends the next roll instead of clearing it out. 
It doesn't actually limit a person on how many re-rolls they want to do. It could, but didn't seem worth the effort, so I am just letting the player decide that. 
If accepted this should close #161
=> Added Support for Multiple Rolls in Enitity Generation

src/datastore/parsers/datasworn/oracles.ts, src/moves/action/action-modal.ts, src/moves/action/index.ts, src/oracles/modal.ts, src/settings/index.ts, src/settings/ui.ts, src/truths/truth-block.ts, src/utils/dice-group.ts, src/utils/dice-overlay.ts, src/utils/dice.test.ts, src/utils/dice.ts
This does what the title says, and also makes it so you can clear out the dice on any keypress in addition to mouse clicking.
This should close #408  and #359
=> Split up the graphic dice settings for oracle and action action dice

src/entity/specs.ts
I'm not sure if the path changed in DS or it was just wrong all along, but this will make settlement entity generation work again.
=> Fixed SI Settlement Entity

src/campaigns/context.ts, src/campaigns/ui/playset-editor.ts, src/characters/action-context.ts, src/datastore.ts, src/datastore/data-context.ts, src/datastore/data-indexer.ts, src/datastore/datasworn-indexer.test.ts, src/datastore/datasworn-indexer.ts, src/datastore/datasworn-symbols.ts, src/datastore/parsers/datasworn/oracles.test.ts, src/datastore/parsers/datasworn/oracles.ts, src/model/oracle.ts, src/moves/action/index.ts, src/moves/move-modal.ts, src/oracles/command.ts, src/oracles/oracle-modal.ts, src/oracles/render.ts, src/sidebar/moves.ts
The original problem here was ensuring that a playset would include an embedded entity when it included the parent entity, in the case that the parent entity was included/excluded based on tags. As a concrete example, `asset:starforged/path/empath` and `asset.ability.move:starforged/path/empath.0.read_heart`. The sundered isles w/ supernatural moves playset should include both, because of the supernatural tag on empath. The ID regex mechanics include both, but the original tag mechanics did not, because the embedded move doesn't have the tag, only the parent asset.
This solves that problem by enriching indexed items with "scopeTags", which merge in all tags from parent entities.
I also needed to solve a similar problem with the move_ruleset index. I did that by tracking the "scope source" …
=> Index scope data

docs/Commands/Advance a clock.md, docs/Commands/Resolve a clock.md, docs/Entities/Clocks.md, src/clocks/commands.ts, src/commands.ts, src/mechanics/css/dlist-clock-status.css, src/mechanics/node-builders/clocks.ts, src/mechanics/node-builders/index.ts
Fixes #224
Also adds a prompt to resolve a clock when it is filled up
=> Resolve a clock command

src/campaigns/context.ts, src/characters/action-context.ts, src/datastore/data-context.ts, src/tracks/progress-create.ts, src/utils/ui/settings/generic-text-suggest.ts
=> Index track categories based on existing moves

src/assets/asset-card.ts, src/assets/css/asset-card.css, src/clocks/clock-block.ts, src/clocks/css/clocks.css, src/clocks/ui/clock-widget.ts
=> Add support for asset ability controls.

src/datastore/parsers/datasworn/id.test.ts, src/datastore/parsers/datasworn/id.ts, src/datastore/parsers/datasworn/oracles.ts, src/model/oracle.ts, src/model/rolls.ts, src/oracles/command.ts, src/oracles/css/oracles.css, src/oracles/modal.ts, src/oracles/new-modal.ts, src/settings/index.ts, src/settings/ui.ts
Presents an oracle table from which you can select the result (or accept the one rolled)
Allows you to drill down into suboracles, such as action+theme, too.
Fixes #429
=> Introduce new oracle roller modal

.gitignore, .gitmodules, CONTRIBUTING.md
The hot-reload plugin directory exists in `test-vault/.obsidian/plugins/` and is somewhat indicated as a submodule in GitHub, but there's no actual submodule set up for it, presumably prevented by exclusion rules in `.gitignore`.
This PR
- adjusts `.gitignore` to explicitly negate exclusion for `test-vault/.obsidian/plugins/hot-reload`
- adds hot-reload as submodule
- mentions it in the `CONTRIBUTING.md` development set up instructions
=> Add hot-reload plugin as submodule

src/clocks/commands.ts
If a clocks's advance odds are set to "Certain", i.e. 100%, rolling dice is skipped now and the clock is instantly advanced, the same way as if it was set to "no roll". Clarify that there's no advance roll happening in the prompt as well.
Fixes #478
=> Clarify clock advance odds

src/datastore/parsers/collection.ts
e.g., "1d6" -> "one_d_six" (instead of "_d_"), "Oracle Array 100" -> "oracle_array_one_zero_zero" (instead of "oracle_array_")
=> Replace numbers with words in homebrew IDs

docs/Other Features/Settings.md, esbuild.config.js, src/character-tracker.ts, src/characters/action-context.ts, src/characters/character-block.ts, src/index.ts, src/link-handler.ts, src/moves/action/index.ts, src/moves/css/move-modal.css, src/moves/move-modal.ts, src/settings/index.ts, src/settings/ui.ts, src/sidebar/css/moves.css, src/sidebar/css/sidebar.css, src/sidebar/css/tab-content-shared.css, src/sidebar/moves.ts, src/sidebar/sidebar-block.ts, src/sidebar/sidebar-view.ts
This changes the moves sidebar to entirely embed the text of moves. Clicking on a move link reveals the sidebar and scrolls to the appropriate move, instead of opening the move modal.
Since this change is still a bit rough around the edges, this also adds a setting _Disable embedding moves in sidebar_ which reverts to the prior modal-centric behavior for the sidebar and for move links.
This accomplishes one-half of issue #476.
=> Embed move text in sidebar

.github/copilot-instructions.md, packages/obsidian/src/oracles/command.ts, packages/obsidian/src/oracles/modal.ts, packages/obsidian/src/oracles/new-modal.ts, vitest.config.js
On desktop, shift+enter will cause the oracle modal to copy the text rather than instert it.
On mobile, you can now swipe a row to reveal action buttons. Swiping left reveals/activates the "accept" button. Swiping right reveals/activates the "copy" button.
Fixes #573
=> Allow copying of raw oracle text from oracle modal
