iron-vault-plugin/iron-vault

src/index.ts
src/moves/action.ts
src/settings/ui.ts
src/utils/editor.test.ts
src/utils/editor.ts

Defaults the move commands to generating blocks in the new KDL mechanics format

Generate mechanics blocks

---

src/datastore/parsers/dataforged.test.ts
src/datastore/parsers/datasworn/oracles.test.ts
src/datastore/parsers/datasworn/oracles.ts
src/datastore/parsers/markdown.ts
src/datastore/parsers/oracle-table.ts
src/datastore/parsers/table.ts
src/datastore/paths.ts
src/datastore/priority-index.ts
src/entity/command.ts
src/model/rolls.ts
src/moves/move-line-parser.ts
src/oracles/modal.ts
src/tracks/progress-create.ts
src/tracks/writer.ts
src/typings/obsidian-ex.d.ts
src/utils/either.ts
src/utils/obsidian.ts
src/utils/tracking-proxy.ts
src/utils/update.ts

Fix lint issues

---

src/moves/action/index.ts
src/utils/strings.test.ts
src/utils/strings.ts

Allow custom move name in "make a move"

---

src/tracks/track-block.ts

Use track APIs for track manipulation

---

src/moves/action/index.ts
src/moves/move-modal.ts

hook up "roll this move" buttons in sidebar and modals

---

src/mechanics/node-builders.ts
src/moves/action/format.ts
src/moves/action/index.ts
src/moves/desc.ts

Change move generation from commands to use `(move:...)` links

---

src/mechanics/node-builders.ts
src/moves/action/index.ts
src/moves/block.ts
src/moves/desc.ts
src/moves/move-modal.ts
src/moves/wrapper.ts

Support "no roll" moves in "make a move"

---

src/tracks/clock-file.ts
src/tracks/clock.test.ts
src/tracks/clock.ts

Clocks can't go to 0?

---

esbuild.config.js
package.json
pnpm-lock.yaml
src/constants.ts
src/mechanics/mechanics-blocks.ts
src/mechanics/node-builders.ts
src/tracks/commands.ts

Various track changes

---

src/characters/action-context.ts
src/characters/lens.test.ts
src/characters/lens.ts

Show asset name in make a move list

---

src/character-tracker.ts
src/characters/commands.ts
src/characters/lens.test.ts
src/characters/lens.ts
src/clocks/clock-create-modal.ts
src/clocks/clock-file.ts
src/clocks/commands.ts
src/constants.ts
src/index.ts
src/indexer/indexer.ts
src/rules/ruleset.ts
src/settings/index.ts
src/settings/ui.ts
src/tracks/commands.ts
src/tracks/progress.ts
src/utils/either.ts
src/utils/obsidian.ts
test-vault/Templates/Character.md
test-vault/Templates/Clock.md

Add new character command with template

---

src/datastore/parsers/datasworn/oracles.ts
src/model/oracle.ts
src/oracles/oracle-modal.ts

Show text2/text3 columns in oracle reference modal

---

src/datastore/parsers/datasworn/oracles.ts
src/index.ts
src/model/oracle.ts
src/moves/action/index.ts
src/oracles/command.ts
src/oracles/oracle-modal.ts
src/settings/index.ts
src/settings/ui.ts
src/sidebar/oracles.ts
src/utils/dice.ts

Fixes #102
This only tackles Make a Move and the initial roll in Ask the Oracle. Asking for more rolls when Roll Twice happens or if you click the re-roll button in the dialog seems like an awkward behavior. I think if we get some heavy dice roll users, we should get them to describe their ideal flow rather than try to guess at it!

Add setting for "bring your own dice"

---

docs/Other Features/Debug Logging.md
package.json
pnpm-lock.yaml
src/api.ts
src/characters/character-block.ts
src/clocks/commands.ts
src/datastore.ts
src/datastore/data-indexer.ts
src/datastore/parsers/datasworn/oracles.ts
src/entity/modal.ts
src/index.ts
src/indexer/indexer.ts
src/indexer/manager.ts
src/logger.ts
src/moves/action/adds-modal.ts
src/moves/action/index.ts
src/moves/block.ts
src/oracles/command.ts
src/sidebar/oracles.ts
src/tracks/commands.ts
src/utils/obsidian.ts
src/utils/suggest.ts
src/utils/ui/prompt.ts

Make logging controllable for devs

---

docs/Other Features/Settings.md
src/characters/css/character-info.css

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/182

fix grid issue with xp earned

---

docs/.obsidian/workspace.json
docs/Blocks/About Blocks.md
docs/Blocks/Truth Blocks.md
docs/Commands/Generate Truths.md
docs/Entities/Truths.md
src/commands.ts
src/datastore.ts
src/datastore/datasworn-indexer.ts
src/index.ts
src/styles.css
src/truths/command.ts
src/truths/css/truths.css
src/truths/truth-block.ts
test-vault/Journals/Chapter 01.md
test-vault/Truths.md

Fixes: https://github.com/cwegrzyn/iron-vault/issues/49

add support for truths

---

src/mechanics/css/details.css
src/mechanics/css/dlist-add.css
src/mechanics/css/dlist-meter.css
src/mechanics/css/dlist-progress.css
src/mechanics/css/dlist-roll.css
src/mechanics/css/dlist-shared.css
src/mechanics/css/dlist-xp.css
src/mechanics/css/mechanics.css
src/mechanics/css/move.css
test-vault/Journals/Chapter 01.md

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/185

Style mechanics blocks so they stand out more even without move nodes

---

docs/.obsidian/workspace.json
docs/Blocks/About Blocks.md
docs/Blocks/Mechanics Blocks.md
src/mechanics/editor.ts
src/mechanics/mechanics-blocks.ts
src/utils/editor.test.ts
src/utils/editor.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/195

rename 'mechanics' block to 'iron-vault-mechanics'

---

src/characters/commands.ts
src/characters/css/asset-list.css
src/characters/css/characters.css
src/sidebar/css/sidebar.css
src/sidebar/css/tab-content-shared.css
src/sidebar/moves.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/178

new, shiny asset picker

---

src/truths/command.ts

It's kinda hard to type your own thing in there otherwise.

insert extra newline between Truths

---

docs/Other Features/Debug Logging.md
package.json
pnpm-lock.yaml
src/api.ts
src/characters/character-block.ts
src/clocks/commands.ts
src/datastore.ts
src/datastore/data-indexer.ts
src/datastore/parsers/datasworn/oracles.ts
src/entity/modal.ts
src/index.ts
src/indexer/indexer.ts
src/indexer/manager.ts
src/logger.ts
src/moves/action/adds-modal.ts
src/moves/action/index.ts
src/moves/block.ts
src/oracles/command.ts
src/sidebar/oracles.ts
src/tracks/commands.ts
src/utils/obsidian.ts
src/utils/suggest.ts
src/utils/ui/prompt.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/171
This reverts commit 72cf08d4fe5ef182ca93b9684de5e77d4ac44e24.

Use loglevel package for controlling logging

---

src/characters/commands.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/215

generate split character sheet by default

---

src/commands.ts
src/mechanics/commands.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/213

add command to easily insert OOC comments

---

src/commands.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/68

add command to insert spoilers

---

src/characters/action-context.ts
src/characters/commands.ts
src/characters/meter-commands.ts
src/commands.ts
src/mechanics/node-builders.ts
src/moves/action/index.ts
src/tracks/commands.ts

Add progress track completion command

---

src/truths/css/truths.css

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/225

make sure truth widget buttons are tall and wide enough

---

src/clocks/clock-block.ts
src/clocks/clock-create-modal.ts
src/clocks/clock-file.ts
src/clocks/clock.test.ts
src/clocks/clock.ts
src/clocks/css/clocks.css
src/tracks/css/tracks.css
src/tracks/track-block.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/70

allow editing of all clock and track fields through widget

---

src/datastore/datasworn-indexer.ts
src/entity/command.ts
src/entity/modal.ts
src/entity/specs.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/229

get planet and settlement entities working

---

src/commands.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/191

reorder commands a bit

---

src/assets/asset-picker-modal.ts
src/characters/character-block.ts
src/settings/ui.ts
src/sidebar/moves.ts

This is just a few initial fixes after adding ironsworn support.

fix a few things with IS support to make the experience smoother

---

src/assets/asset-card.ts
src/index.ts
src/oracles/render.ts
src/settings/ui.ts

https://github.com/iron-vault-plugin/iron-vault/issues/251

enable switching rulesets without having to  reload

---

esbuild.config.js
package.json
pnpm-lock.yaml
src/api.ts
src/datastore.ts
src/datastore/datasworn-indexer.ts
src/datastore/parsers/datasworn/oracles.ts
src/entity/modal.ts
src/index.ts
src/iron-vault.d.ts
src/model/oracle.ts
src/model/rolls.ts
src/moves/action/index.ts
src/oracles/command.ts
src/oracles/modal.ts
src/oracles/render.ts
src/oracles/roller.ts
src/settings/index.ts
src/settings/ui.ts
src/styles.css
src/truths/truth-block.ts
src/utils/dice-group.ts
src/utils/dice-overlay.ts
src/utils/dice.test.ts
src/utils/dice.ts
src/utils/overlay-dice.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/44

graphical dice roller

---

src/entity/modal.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/257

need to async-wait for entity rolls

---

src/utils/dice-overlay.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/263
I don't know _why_ this fixes it, but I think the files were somehow getting corrupted by loading? idek

rewrite asset files on every load

---

package.json
pnpm-lock.yaml
src/clocks/clock-create-modal.ts
src/entity/command.ts
src/entity/modal.ts
src/entity/specs.ts

Allow configuration of filename/dir for entity generation, just like with clocks/tracks

---

src/entity/command.ts
src/entity/specs.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/262
Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/261

filter entities by ruleset and add an IS ent

---

data/starforged.supplement.json
data/starforged.supplement.yaml
docs/Commands/Generate an entity.md
docs/Entities/Factions.md
package.json
src/datastore.ts
src/datastore/data-indexer.ts
src/datastore/datasworn-indexer.ts
src/entity/modal.ts
src/entity/specs.ts

Fixes #151
(Pending a fix on names)

Finish faction entity generation

---

docs/.obsidian/workspace.json
docs/Blocks/Mechanics Blocks.md
src/characters/character-block.ts
src/characters/commands.ts
src/characters/lens.test.ts
src/characters/lens.ts
src/datastore.ts
src/mechanics/css/dlist-initiative.css
src/mechanics/css/mechanics.css
src/mechanics/mechanics-blocks.ts
src/rules/ruleset.ts
test-vault/Journals/Chapter 02.md

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/242

Add support for initiative/position

---

src/settings/index.ts
src/settings/ui.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/283

add settings button to reset settings to their defaults

---

src/commands.ts
src/mechanics/mechanics-blocks.ts
src/moves/action/action-modal.ts
test-vault/Journals/Chapter 02.md

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/265

add die reroll command

---

src/characters/commands.ts
src/commands.ts
src/mechanics/node-builders.ts

Add command for changing initiative/position

---

src/tracks/track-block.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/296

properly select progress track rank on load

---

src/mechanics/css/dlist-shared.css
src/mechanics/mechanics-blocks.ts
src/settings/ui.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/291

change challenge die colors in mechanics blocks according to settings

---

src/assets/asset-modal.ts
src/entity/modal.ts
src/moves/move-modal.ts
src/oracles/oracle-modal.ts
src/styles.css

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/310

allow text selection inside modals

---

src/characters/css/stats.css
src/moves/action/index.ts
src/moves/css/move-modal.css
src/moves/move-modal.ts
src/styles.css

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/271

add clickable stat buttons to move modal

---

src/moves/move-modal.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/327

add button to roll move-related oracles directly from the move modal

---

src/migrate/migration-0_0_10-0_1_0.test.ts
src/migrate/migration-0_0_10-0_1_0.ts

Fix bad substitution during migration

---

src/migrate/css/migrate.css
src/migrate/migration-view.ts

This is not _that_ much better, but it's a little better I think?
Fixes #338

Migrate page buttons look bad on mobile

---

src/utils/dice-overlay.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/340

only clear dice after they're done rolling

---

src/clocks/commands.ts
src/clocks/select-clock.ts
src/commands.ts
src/mechanics/node-builders.ts
src/moves/action/index.ts
src/tracks/commands.ts
src/tracks/select.ts
src/utils/strip-markdown.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/100

strip markdown from track/clock node links

---

src/characters/lens.test.ts
src/characters/lens.ts

Use sensible defaults for stats, meters, and tracks when loading characters

---

docs/Commands/Make a move.md
src/moves/action/index.ts

Allow skipping action move rolls

---

src/datastore/parsers/datasworn/oracles.ts
src/model/rolls.ts
src/oracles/modal.ts
src/settings/index.ts
src/settings/ui.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/350

allow disabling and rerolling cursed die

---

src/datastore.ts
src/datastore/datasworn-indexer.ts
src/moves/action/index.ts
src/oracles/command.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/353

Show source ruleset when using make a move command

---

src/characters/character-block.ts
src/characters/css/assets.css

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/319

play around with asset list alignment and move add asset button out

---

src/sidebar/css/oracles.css
src/sidebar/oracles.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/355

be clearer about Roll All vs individual rolls

---

src/entity/command.ts
src/entity/modal.ts
src/entity/specs.ts

I forgot to update the entity specs for Datasworn 0.1.0. Oops! That broke entities entirely. This fixes that up.

Update entities to datasworn 0.1.0

---

esbuild.config.js
package.json
src/link-handler.ts

Oracle links don't seem to work on mobile

---

src/link-handler.ts

Link handler should use raw href

---

src/settings/local.ts

Safer handling of missing local settings file

---

src/moves/action/action-modal.ts

Reroll should work with actor nodes

---

docs/Commands/Change position or initiative.md
docs/Commands/index.md
src/commands.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/301

document the position/initiative change command and rename it

---

src/moves/move-modal.ts
src/oracles/css/oracles.css
src/oracles/oracle-modal.ts
src/oracles/render.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/335

style oracle tables a bit nicer

---

src/entity/specs.ts

Added in a Settlement Entity for Sundered Isles.

Added Sundered Isles Settlement Entity

---

src/tracks/commands.ts
src/tracks/progress-create.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/389

fix issue with track-type not being saved

---

src/entity/specs.ts

Adds the Starforged Settlement entity since someone was asking about it on Discord

Added Starforged Settlement Generator

---

src/tracks/progress-create.ts
src/utils/ui/settings/generic-text-suggest.ts

Fixes an issue where the Track Type wouldn't be set when creating a new Progress Track

Fixed Setting Track Type when Picking from AutoSuggest

---

src/characters/character-block.ts
src/characters/css/character-info.css
src/characters/lens.test.ts
src/characters/lens.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/400
Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/329

add player name and manual xp fields

---

src/mechanics/css/details.css
src/mechanics/css/mechanics.css
src/mechanics/css/oracle-group.css
src/mechanics/mechanics-blocks.ts

this is just laying groundwork for other stuff I want to do

move mechanics rendering over to lit-html

---

src/mechanics/mechanics-blocks.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/407

add deletion support to mechanics blocks and individual nodes

---

data/starforged.supplement.json
data/starforged.supplement.yaml
data/sundered-isles.supplement.json
data/sundered-isles.supplement.yaml

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/276

hack in incidental vehicles

---

src/assets/asset-card.ts
src/assets/css/asset-card.css
src/moves/css/move-modal.css
src/moves/move-modal.ts
src/oracles/css/oracles.css
src/oracles/oracle-modal.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/406

add ruleset info to assets/moves/oracles

---

src/mechanics/mechanics-blocks.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/323

sortable mechanics block entries

---

package.json
pnpm-lock.yaml
src/datastore.ts
src/mechanics/mechanics-blocks.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/431

update sundered-isles package name

---

src/mechanics/mechanics-blocks.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/441

fix issues with node dragging

---

src/entity/specs.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/436

SI faction entities

---

src/campaigns/commands.ts
src/campaigns/ui/new-campaign-modal.ts
src/characters/commands.ts
src/truths/command.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/299

support more thorough scaffolding on campaign creation

---

LICENSE.md
package.json
pnpm-lock.yaml

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/438

move to datasworn@next packages and update licensing

---

src/commands.ts
src/constants.ts
src/factions/commands.ts
src/factions/grid-creation-modal.ts

Fixes: https://github.com/iron-vault-plugin/iron-vault/issues/240

add faction influence grid generator

---

src/character-tracker.ts
src/characters/action-context.ts
src/characters/assets.test.ts
src/characters/assets.ts
src/characters/errors.ts
src/characters/lens.test.ts
src/characters/lens.ts
src/utils/lens.ts
test-vault/CampaignSI/Characters/Jack Sparrow.md

Support for "enhance asset" in asset attributes

---

src/entity/command.ts
src/oracles/command.ts
src/settings/index.ts
src/settings/ui.ts

I've kicked the tires on the new roller enough that I feel comfortable rolling it out. This renames the property (to blow away the old default) and defaults it to using the new roller.

Default to new oracle roller

---

src/datastore.ts

Currently does the most naive thing: if anything in a homebrew folder hierarchy changes, rebuild and reload the whole package. Brute force, but it's a starting point!

Auto-reload homebrew content on modification

---

src/oracles/new-modal.ts

Add rolled result and reroll button to new roller

---

src/utils/dice-roller.ts
test-vault/Homebrew/CampaignSI/arrays/New Oracle.md
test-vault/Homebrew/CampaignSI/arrays/Oracle Array 1.md

h/t to Conspite on discord for noticing

Fix dice roller when rolling NdM for N > 1

---

.vscode/settings.json
src/settings/index.ts
src/settings/ui.ts
src/utils/dice-group.test.ts
src/utils/dice-group.ts
src/utils/dice-overlay.ts
src/utils/dice-roller.ts
src/utils/dice.test.ts
src/utils/dice.ts
test-vault/Homebrew/CampaignSI/arrays/1d36 Oracle.md

Implements an overly complicated dice expression system in order to transform non-standard dice into ones we can roll
Fixes #498

Factor non-standard dice into ones we can roll

---

docs/Other Features/Settings.md
src/iron-vault.d.ts
src/settings/index.ts
src/settings/ui.ts
src/styles.css
src/utils/dice-overlay.ts

Add options to auto-hide dice and enable dice clickthrough

---

docs/Campaigns/Creating a campaign.md
docs/Campaigns/Playsets/index.md
docs/Other Features/Rulesets and Homebrew.md
src/assets/asset-block.ts
src/campaigns/campaign-source.ts
src/campaigns/commands.ts
src/campaigns/context.ts
src/campaigns/entity.ts
src/campaigns/manager.ts
src/campaigns/ui/edit-view.ts
src/campaigns/ui/new-campaign-modal.ts
src/datastore.ts
src/datastore/data-indexer.ts
src/datastore/parsers/collection.ts
src/mechanics/mechanics-blocks.ts
src/settings/index.ts
src/sidebar/sidebar-block.ts
src/sidebar/sidebar-view.ts
src/truths/truth-block.ts
src/utils/filename.ts
src/utils/ui/settings/relative-folder-search.ts
src/utils/versioned-map.test.ts
src/utils/versioned-map.ts
test-vault/Campaign 1/Custom Content/Foo/Custom Oracle.md
test-vault/Campaign 1/My first campaign.md
test-vault/Campaign 2/Custom Content/Foo/Custom Oracle.md

Support campaign-specific custom content

---

docs/Commands/Set action roll challenge dice sides.md
docs/Commands/index.md
src/campaigns/context.ts
src/commands.ts
src/moves/action/action-modal.ts
src/moves/action/index.ts
src/settings/local.ts

Add command that lets you override challenge dice sides

---

src/entity/new-modal.ts

Fix entity modal for entities without first look

---

esbuild.config.js
src/datastore/loader/builder.ts
src/datastore/loader/nodes.ts
src/datastore/parsers/markdown.ts

Improve Homebrew inspector support for markdown file errors

---

.vscode/settings.json
src/campaigns/campaign-source.ts
src/character-tracker.ts
src/mechanics/mechanics-blocks.ts
src/settings/local.ts
src/sidebar/character.ts
src/sidebar/content-tree.ts
src/sidebar/css/oracles.css
src/sidebar/css/sidebar.css
src/sidebar/moves.ts
src/sidebar/oracles.ts
src/sidebar/sidebar-block.ts
src/sidebar/sidebar-view.ts
test-vault/CampaignSI/Characters/Jane Sparrow.md

- Fixes a bug that prevented the character sidebar from updating when active character changed
- Switches the search box in moves/oracle tabs to standard Obsidian components, including the "clear" button
- Adds a collapse all/expand all button to moves/oracles tabs
- Behind the scenes, a major refactor of the sidebar to hopefully make it faster, more resilient, and easier to maintain!

Sidebar quality of life improvements and fixes

---

package.json
packages/datasworn-compiler/src/builder.test.ts
packages/obsidian/package.json
packages/obsidian/src/campaigns/campaign-source.ts
packages/obsidian/src/moves/move-modal.ts
packages/obsidian/src/sidebar/character.ts
packages/obsidian/src/sidebar/moves.ts
packages/obsidian/src/sidebar/oracles.ts
pnpm-lock.yaml

Reflect changes to characters in move sidebar buttons

---

packages/datasworn-compiler/src/builder.ts

yaml reuses objects when aliases are in place. structuredClone preserves that object reuse. This means that when the Datasworn compiler mutates the objects, it can lead to issues (in particular, ID assignment). Using JSON.parse/stringify duplication decouples the objects

Use JSON.parse/stringify to break aliases

---

packages/obsidian/package.json
packages/obsidian/src/datastore/loader/data-loader.worker.ts
packages/obsidian/src/index.ts
pnpm-lock.yaml

Hopefully fixes issues on Android with older Chrome versions that lack these. Also, now I get to use them willy-nilly?

Shim iterator helpers

---

packages/obsidian/src/characters/action-context.ts
packages/obsidian/src/sidebar/moves.ts

Show asset moves in sidebar

---

packages/obsidian/src/sidebar/css/sidebar.css
packages/obsidian/src/sidebar/css/tab-content-shared.css
packages/obsidian/src/sidebar/sidebar-view.ts

Also tweaks the styling of the nav header to better align with Obsidian standard styles.
Fixes #552

Switch sidebar to move tab when clicking on a move link

---

packages/obsidian/src/sidebar/moves.ts

Hide sidebar after making move on mobile
